(let (;; 加载的时候临时增大`gc-cons-threshold'以加速启动速度。
      (gc-cons-threshold most-positive-fixnum)
      ;; 清空避免加载远程文件的时候分析文件。
      (file-name-handler-alist nil))
  (with-temp-buffer
    ""
    (require 'init-generic)
    (require 'init-font)
    (require 'init-emacs)
    (require 'lazy-load)
    (require 'one-key)
    (require 'meow)
    (require 'init-one-key)
    (require 'init-key)
    (require 'init-meow)
    (require 'init-better-default)
    ;; Emacs配置文件内容写到下面.
    ;; 延迟加载
    (run-with-idle-timer
     1 nil
     #'(lambda ()
	 (require 'init-grammatical-edit)
	 (require 'init-window)
	 (require 'init-ui)
	 (require 'init-no-littering)
	 (require 'init-orderless)
	 (require 'init-corfu)
	 (require 'init-vertico)
	 (require 'init-awesome-tray)
	 (require 'init-minibuffer-modifier-keys)
	 (require 'init-dirvish)
	 (require 'init-format-all)
	 (require 'init-auto-save)
	 (require 'init-xref)
	 (require 'init-web)
	 (require 'init-helpful)
	 (require 'init-telega)
	 (require 'init-disable-mouse)
	 (require 'init-hide-mode-line)
	 (require 'init-rime)
	 (require 'init-web)
	 (require 'init-go-translate)
	 (require 'init-crow)
	 (require 'init-bongo)
	 (require 'init-project)
	 (require 'init-magit)
	 (require 'init-lsp-bridge)
	 (require 'init-typescript)
	 (require 'init-rust)
	 ))
    ))
(provide 'init-config)
