;; 打开emacs后必须立刻使用的
(require 'init-func)
(require 'init-ui)
(require 'init-mode)
(require 'init-hooks)
(require 'init-one-key)
(require 'init-ediff)
(require 'init-treesit)
(require 'init-rime)
(require 'init-key)
(require 'init-window)
(require 'init-helpful)
(require 'init-xref)
(require 'init-auto-save)
(require 'init-translate)
(require 'init-flycheck)
(require 'init-lsp)
(require 'init-elfeed)

;; 启动1s后再开启gc管理
(run-with-idle-timer 0.2 0 (lambda ()
			   (require 'init-meow)
			   (require 'init-corfu)
			   (require 'init-minibuffer-completion)
			   (goggles-mode t)
			   (require 'init-gcmh)))

;; (benchmark-init/deactivate)

(provide 'init-config)
